#!/bin/bash
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --gres=gpu:1
#SBATCH --time=04:00:00
export THEANO_FLAGS="device=gpu"
source ~/.myworkrc
source activate py3
source ~/.cudarc_new
python --version
nvcc --version
dev=$(nvidia-smi |grep 0MiB -B1|awk '{print $2}'|head -n 1)
echo $dev
echo $1
if [ -z "$1" ]; then
    SRC="dataset"
else
    SRC=$1
fi
PREFIX="opt_$SRC"
ARGV="--data-source=$SRC"
CUDA_VISIBLE_DEVICES=$dev codeopt --folder-prefix=$PREFIX --argv=$ARGV --bayesopt --optim=maximize --verbose=1 compressor.py
